### ISSUE TITLE
`ethv --list` latestRelease: 0.4.21

### ISSUE THREAD

**Issue by burrrata** [ConsenSys/bytecode-verifier#12]
This tool seems amazing, but also not maintained. 

`$ ethv --list`

================================

latestRelease: 0.4.21

Here is a list of solc versions from formal major releases:

0.4.21 : v0.4.21+commit.dfe3193c
0.4.20 : v0.4.20+commit.3155dd80
0.4.19 : v0.4.19+commit.c4cbbb05
0.4.18 : v0.4.18+commit.9cf6e910
0.4.17 : v0.4.17+commit.bdeb9e52
0.4.16 : v0.4.16+commit.d7661dd9
0.4.15 : v0.4.15+commit.bbb8e64f
0.4.14 : v0.4.14+commit.c2215d46
0.4.13 : v0.4.13+commit.fb4cb1a
0.4.12 : v0.4.12+commit.194ff033
0.4.11 : v0.4.11+commit.68ef5810
0.4.10 : v0.4.10+commit.f0d539ae
0.4.9 : v0.4.9+commit.364da425
0.4.8 : v0.4.8+commit.60cc1668
0.4.7 : v0.4.7+commit.822622cf
0.4.6 : v0.4.6+commit.2dabbdf0
0.4.5 : v0.4.5+commit.b318366e
0.4.4 : v0.4.4+commit.4633f3de
0.4.3 : v0.4.3+commit.2353da71
0.4.2 : v0.4.2+commit.af6afb04
0.4.1 : v0.4.1+commit.4fc6fc2c
0.4.0 : v0.4.0+commit.acd334c9
0.3.6 : v0.3.6+commit.3fc68da
0.3.5 : v0.3.5+commit.5f97274
0.3.4 : v0.3.4+commit.7dab890
0.3.3 : v0.3.3+commit.4dc1cb1
0.3.2 : v0.3.2+commit.81ae2a7
0.3.1 : v0.3.1+commit.c492d9b
0.3.0 : v0.3.0+commit.11d6736
0.2.2 : v0.2.2+commit.ef92f56
0.2.1 : v0.2.1+commit.91a6b35
0.2.0 : v0.2.0+commit.4dc2445
0.1.7 : v0.1.7+commit.b4e666c
0.1.6 : v0.1.6+commit.d41f8b7
0.1.5 : v0.1.5+commit.23865e3
0.1.4 : v0.1.4+commit.5f6c3cd
0.1.3 : v0.1.3+commit.28f561
0.1.2 : v0.1.2+commit.d0d36e3
0.1.1 : v0.1.1+commit.6ff4cd6

<br>

Why did you guys stop maintaining the `bytecode-verifier` and/or was it incorporated into some other toolkit?

**Comment by shayanb** [comment]
Seems to be fixed for multi contract files now. Needs more testing for different solidity versions as the byte code prefixes might break things.
