### ISSUE TITLE
Verify inherited contracts

### ISSUE THREAD

**Issue by dimorinny** [ConsenSys/bytecode-verifier#6]
Hi, @AlexXiong97. Thanks for great library.

As I understand, when my contract imports another contracts, you verify only contract, that has the same name as a file. In this case main contract may has a many parents and for every parent, swarm hash will be generated.

But I found, that in your source code:

```
var ending_point = bytecode.search('a165627a7a72305820');
```
you don't check all bytecode after first swarm hash.

**Is it right?**

For example, for [this](https://kovan.etherscan.io/address/0xc2e5a20673803fc1df4c71d98a56cefa33a2d0e8#code) contract, you may check all bytecode (include parents) if you remove the whole swarm information instead of getting substring before first swarm.

Thanks a lot.

**Comment by AlexXiong97** [comment]
@dimorinny Thank you for the issue, the original code has some minor problem dealing with multiple swarm hashes in the bytecode. 

Here is the [new commit](https://github.com/ConsenSys/bytecode-verifier/commit/29dedd60fedb71c59090642c069cb2f7de99617a#diff-13a26c29d16405f6e694991a87084025R92) I tried to fix that:

Plus with [explanation](https://github.com/ConsenSys/bytecode-verifier/blob/master/BYTECODE_EXPLAINED.md) 

Hope it helps clarify. If any further question, feel free to brought up, always happy to answer.

Cheers!
