### ISSUE TITLE
Link references support

### ISSUE THREAD

**Issue by dimorinny** [ConsenSys/bytecode-verifier#8]
I tried to verify contract from [there](https://etherscan.io/address/0xe2cc64efb6c1fabb09fe6e59eba6df2dacb92915#code) and found, that compiled contract has link references to SafeMathLibExt in bytecode. But blockchain doesn't have this information.

Maybe you may know, for what reason we have it in compiled bytecode and why we don't have it on deployed bytecode?

**Comment by headfire94** [comment]
probably duplicate #4
